### ISSUE TITLE
Dodanie kontrolek dotykowych na android

### ISSUE THREAD

**Issue by MikDal002** [filerd002/BattleTank#12]
Proponuję takie sterowanie: 
 
- czołg jeździ za palcem, im dalej palec tym szybciej,
- natomiast druga ręka przy naciśnięciu krótkim strzela, natomiast przy długi stawia minę.

Czekam na inne propozycje :).

**Comment by MikDal002** [comment]
Dobra, biorę się za to ;).

**Comment by filerd002** [comment]
#71
