### ISSUE TITLE
Zmiana wielkości gry zależnie od ekranu

### ISSUE THREAD

**Issue by MikDal002** [filerd002/BattleTank#13]
Gra powinna dostosywać się automatycznie do wielkości ekranu. Aktualny model powoduje, że gra na mniejszych ekranach zamienia się po prostu w maczek.

== EDIT == 
A może wogóle zrobić menu, które pozwala użytkownikowi wybrać wielkość mapy?

**Comment by filerd002** [comment]
Wykonane gdzieś w trakcie pracy
