### ISSUE TITLE
Zwiększone obciążenie gry i spadek liczby klatek przy większej ilości kul w grze

### ISSUE THREAD

**Issue by MikDal002** [filerd002/BattleTank#18]
Zauważyłem, że, kiedy włączysz maksymalną ilość czołgów (jednego i drugiego typu) to gra szybko zaczyna się przymulać. Po wstępnej analizie obciążenia CPU problemem zaczyna być update pocisków.

**Comment by filerd002** [comment]
Pociski ulegające kolizji z przeszkodą lub czołgiem ulegają zniszczeniu, problem może pojawiać aie gdy ramka mapy nie jest pełna, warto sprawdzić co dzieje sie z pociskami, gdy znajdą się poza mapą. 

-Ograniczenie długości lotu pocisku zmniejszy ich ilość
-wprowadzenie asynchroniczności dla wywoływania metody Fire(),  przez czołgi Cpu  (w obecnej chwili wszystkie czołgi Cpu strzelają w tym samym momęcie)

**Comment by filerd002** [comment]
#25

**Comment by MikDal002** [comment]
#52 Poprawka ta dodatkowo usuwa wszystkie pociski i miny które już zakończyły swój żywot.
