### ISSUE TITLE
Miganie tarczy kiedy kończy się czas

### ISSUE THREAD

**Issue by MikDal002** [filerd002/BattleTank#22]
Taki pomysł, aby tarcza chroniąca czołg migała jakiś krótki okres czasu przed tym jak zniknie. Pozwoli to użytkownikowi lepiej zaplanować swoje własne działanie.

**Comment by filerd002** [comment]
Tarcza działa przez 10 sekund, miganie dla 3, 2, 1 ?

**Comment by MikDal002** [comment]
Na przykład :). Myślę, że dałoby to uzytkownikowi ciekawy feedback :).

**Comment by MikDal002** [comment]
Myślę, że mogę to wziąć na siebie :).
