### ISSUE TITLE
Usunięcie Tank2 z planszy w trakcie gry jednoosobowej.

### ISSUE THREAD

**Issue by MikDal002** [filerd002/BattleTank#24]
Czasem podczas pracy nad AI występuje problem, że komputer gubi się, bo chce atakować czołg gracza 2. Dlatego właśnie z chęcią bym go usunał, tak aby nie było takiej możliwości i występował w systemie jako "null". Zresztą odpowiednia implementacja pozwoli nam otworzyć się na większą ilość żywych graczy niż 2. Może się to przydać jak na Andku chcielibyśmy wlączyć grę wieloosobową :).

**Comment by filerd002** [comment]
# #25
