### ISSUE TITLE
Kolor osłony zależny od koloru gracza

### ISSUE THREAD

**Issue by MikDal002** [filerd002/BattleTank#42]
Co myślisz o takiej zmianie, aby kolor osłony był taki sam jak kolor gracza?

**Comment by filerd002** [comment]
Spoko. Jest to do zrobienia małym kosztem czasu :) Należało by zmienić kolor tekstury bariery na biały następnie zakładać kolor programowo w funkcji draw() zależnie od koloru czołgu.

**Comment by MikDal002** [comment]
Dobra, biorę to na siebie :D. Od razu zrobię też parę refaktoryzacji aby uprościć kod :).
