### ISSUE TITLE
Dodanie enuma dla stanów gry

### ISSUE THREAD

**Issue by MikDal002** [filerd002/BattleTank#48]
Proponuję aby stany gry opisać za pomocą enumów a nie intów. Dzięki temu uzyskamy większą przejrzystość oraz współpracę z IDE.

https://github.com/filerd002/BattleTank/blob/a1d79eb1020ea8f1af10c9968f1e756ba9b31dc3/BattleTank.Core/Game1.cs#L113-L114

**Comment by filerd002** [comment]
Zajmę się tym

**Comment by filerd002** [comment]
Zmienię także w klasach PowerUp oraz Tile, pola type z int na emum

**Comment by filerd002** [comment]
#62
