### ISSUE TITLE
Porzadkowanie systemu Powerup ciągl dalszy

### ISSUE THREAD

**Issue by MikDal002** [filerd002/BattleTank#59]
[#49]

Myślę, że dobrze byłoby przenieść ten kod do klasy PowerUp.cs :).
 
https://github.com/filerd002/BattleTank/blob/a1d79eb1020ea8f1af10c9968f1e756ba9b31dc3/BattleTank.Core/Game1.cs#L388-L409

**Comment by filerd002** [comment]
#68
